version: '2'
services:
  academy-proxy:
    image: capinzonr/sa_academy_proxy
    depends_on:
      - academy-api
    ports:
      - "80:80"
  academy-api:
    image: capinzonr/sa_academy_api
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_PORT: '4000'
      AUTH_ENTRY: 'ldap/'
      STUDENTS_PORT: '4000'
      STUDENTS_ENTRY: 'students/'
      COURSES_PORT: '4001'
      COURSES_ENTRY: 'courses/'
      GRADES_PORT: '4002'
      GRADES_ENTRY: 'grades/'
  students-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: students
      MYSQL_HOST: students-db
  students-ms:
    image: capinzonr/sa_students_ms
    command: bash -c "sleep 160 && rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
    environment:
      PORT: '4000'
    depends_on:
      - students-db
  courses-db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: courses
      MYSQL_HOST: courses-db
  courses-ms:
    image: capinzonr/sa_courses_ms
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 4001 -b '0.0.0.0'"
    environment:
      PORT: '4001'
    depends_on:
      - courses-db
  grades-db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: grades
      MYSQL_HOST: grades-db
  grades-ms:
    image: capinzonr/sa_grades_ms
    command: bash -c "sleep 160 && rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 4002 -b '0.0.0.0'"
    environment:
      PORT: '4002'
    depends_on:
      - grades-db
  academy-ldap:
    image: osixia/openldap:1.1.8
    container_name: academy-ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 100000
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"

    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.org"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "academy-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - academy-ldap
